### PCR Test Sonucunu Yapay Sinir Ağları ile Test Etme

Problem: Pcr test sonucu verilen 14 kişinin 7 farklı hastalık belirtileri var ya da yok olarak verilmiştir. Gizli katmansız yapay sinir ağı kurarak yeni hastalık belirtileri bilinen kişilerin Pcr test sonucunu tahmin edelim.

6 input, 1 output ve gizli katmansız yapay sinir ağları yapısında ağırlıklar 0.1, 0.1, 0.1, 0.3, 0.15,0.25 olarak girilmiştir.

In [3]:
import numpy as np
input_ozellikleri = np.array([[1,1,1,1,0,1],[1,0,1,1,1,1],[1,1,0,1,1,1],
                            [0,1,0,1,0,1],[0,0,0,0,1,1],[0,0,1,0,0,0],
                            [1,1,0,1,1,1],[1,0,0,0,0,1],[0,1,0,0,0,1],
                            [0,1,1,1,1,1],[0,0,1,1,1,1],[1,1,0,0,0,1],
                            [1,1,1,1,1,1],[1,0,0,1,0,0]])

In [4]:
print(input_ozellikleri.shape)
input_ozellikleri

(14, 6)


array([[1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1],
       [1, 1, 0, 1, 1, 1],
       [0, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 1, 1],
       [0, 0, 1, 0, 0, 0],
       [1, 1, 0, 1, 1, 1],
       [1, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 1],
       [0, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1],
       [1, 1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 0, 0, 1, 0, 0]])

In [5]:
# Hedef Output Tanimlama
hedef_output = np.array([[1,1,1,0,0,0,1,0,0,1,1,0,1,0]])

In [6]:
# Hedef Degişkeni Vektore Donusturme
import numpy as np
hedef_output = hedef_output.reshape(14,1)
print(hedef_output.shape)
print(hedef_output)

(14, 1)
[[1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]]


In [7]:
# Agirliklari Tanimlama
agirliklar = np.array([[0.1],[0.1],[0.1],[0.3],[0.15],[0.25]])
print(agirliklar.shape)
print(agirliklar)

(6, 1)
[[0.1 ]
 [0.1 ]
 [0.1 ]
 [0.3 ]
 [0.15]
 [0.25]]


In [8]:
# Sigmoid Fonk.
def  sigmoid(x):
    return 1/(1+np.exp(-x))
# Sigmoid fonk. türevi
def sigmoid_der(x):
    return sigmoid(x)*(1-sigmoid(x))

In [9]:
# Yanlilik Agirligi
yanlilik = 0.3
#Ogrenme Orani
lr = 0.05

In [ ]:
# Sinir Aglari Yapisi
# Kodları 10000 defa calistirma
for epoch in range(10000):
    inputlar = input_ozellikleri
    
    #İleri Besleme input
    tahmin_input = np.dot(inputlar, agirliklar) + yanlilik
    
    #output
    tahmin_output = sigmoid(tahmin_input)
    
    #Geri yayilim
    #Hatayi hesaplama
    hata = tahmin_output - hedef_output
    x = hata.sum()
    print(x)

   #Turevi Hesaplama
    dcost_dpred = hata
    dpred_dz = sigmoid_der(tahmin_output)
    
    # Kismi Turevleri Hesaplama
    z_delta = dcost_dpred * dpred_dz
    
    # 3.dereceden kısmi turevleri hesaplama
    inputlar = input_ozellikleri.T
    agirliklar -= lr * np.dot(inputlar, z_delta)
    
    # Yanlilik Agirlik Degeri Guncelleme
    for i in z_delta:
        yanlilik -= lr * i



In [11]:
# Tahmin Agirliklari ve Yanliligi Yazdirma
print(agirliklar)

[[2.81750758e+00]
 [2.86138730e+00]
 [5.81378253e+00]
 [3.63433841e+00]
 [6.23859052e+00]
 [5.29082798e-03]]


In [12]:
print(yanlilik)

[-10.81421645]


Model kurulduktan sonra yeni özellik değerleri girilen PCR test sonuçları tahmin edilebilir.

In [13]:
# Yeni inputlar girme
yeni_ozellikler = np.array([1,0,0,1,1,1])

# İlk adim
tahmin1 = np.dot(yeni_ozellikler, agirliklar) + yanlilik

# İkinci adim
tahmin2 = sigmoid(tahmin1)

#Sonuc tahmini yazdirma
print(tahmin2)

[0.86778457]


Yorum: Olasılık 0.9061 > 0.5 olduğundan tahmin 1  olarak yani pozitif olarak sınıflandırılır.

In [14]:
# Yeni inputlar girme
yeni_ozellikler = np.array([0,0,0,1,1,1])

# İlk adim
tahmin1 = np.dot(yeni_ozellikler, agirliklar) + yanlilik

# İkinci adim
tahmin2 = sigmoid(tahmin1)

#Sonuc tahmini yazdirma
print(tahmin2)

[0.2817097]


Yorum: Olasılık değeri 0.2114 < 0.5 olduğundan tahmin 0 olarak yani negatif olarak sınıflandırılır.

In [15]:
# Yeni inputlar girme
yeni_ozellikler = np.array([1,0,1,1,1,1])

# İlk adim
tahmin1 = np.dot(yeni_ozellikler, agirliklar) + yanlilik

# İkinci adim
tahmin2 = sigmoid(tahmin1)

#Sonuc tahmini yazdirma
print(tahmin2)

[0.99954524]


Yorum: Olasılık değeri 0.9999 > 0.5 olduğundan tahmin 1 olarak yani pozitif olarak sınıflandırılır.